version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    assignees:
      - "@jlwainwright"
    reviewers:
      - "@jlwainwright"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore patch updates for these packages to reduce noise
      - dependency-name: "pytest"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "black"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    assignees:
      - "@jlwainwright"
    reviewers:
      - "@jlwainwright"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 5

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    assignees:
      - "@jlwainwright"
    reviewers:
      - "@jlwainwright"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5